version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.17.4
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.17.4
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Unit Tests
          command: yarn ci:test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run:
          name: ESLint
          command: yarn ci:eslint
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - run:
          name: Unit Test Coverage
          command: yarn ci:coverage
      - store_artifacts:
          path: coverage
  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.17.4
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn build
      - run:
          name: Tag and Publish Version
          command: yarn ci:release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
